### ISSUE TITLE
Startup Loading Screen not playing on load but in place of default

### ISSUE THREAD

**Issue by cckelly** [truong-bui/AsyncLoadingScreen#109]
Hey @truong-bui, fantastic plugin although I’m hitting some strange issues when we try to use it in Lyra-based game. I’ve ripped out CommonLoadingScreen so that causing issues shouldn’t be a problem here:

- `FDefaultGameMoviePlayer::HasEarlyStartupMovie` always returns false although looking at `PLATFORM_SUPPORTS_EARLY_MOVIE_PLAYBACK` on Windows should always be 1. I can force this to return true and it plays my startup loading screen (albeit with some flickering), however I think I’m missing something. Toggling on and off Allow in Early Startup makes no difference either.
- If I don’t do that and leave the engine code as is, the startup loading screen is skipped entirely and is instead played where the default loading screen should occur (going into a match for example).

Any help would be greatly appreciated, thanks in advance! We are building from engine source that’s on 5.3.2 with the 5.3.0 branch of the plugin checked out.

**Comment by truong-bui** [comment]
Hi, please make sure that no plugin (for example, Pre-Load Screen Movie Player plugin) is using MoviePlayer, which can cause a conflict with the Async Loading Screen.

I have checked the` PLATFORM_SUPPORTS_EARLY_MOVIE_PLAYBACK` and see that it is assigned the value of `(!WITH_EDITOR)` (1) which is always false(0) if you run on Editor. Have you tested your game in the packaged game yet?
![image](https://github.com/user-attachments/assets/9bb96340-172a-4f44-aa3e-bc48c76ce620)

Unfortunately, this is related to the MoviePlayer module, which is out of my ability to fix.

**Comment by cckelly** [comment]
Hi @truong-bui, thanks for the response! We actually do have the Pre-Load Screen Movie Player plugin, disabling it fixed it! Thank you so much!
