### ISSUE TITLE
Memory leak while allowing player to wait in loading screen on UE 4.25.4

### ISSUE THREAD

**Issue by terishrimp** [truong-bui/AsyncLoadingScreen#20]
Hey Truong, these settings will cause a Windows 64-bit build to leak memory if you stay on the loading screen:
-  Wait For Manual Stop = true
- Minimum Loading Screen Display Time = -1
- Auto Complete When Loading Completes = false
- Movies are Skippable = false
- Allow in Early Start = false
- Allow Engine Tick = false

I did a memreport both before and after the loading screen and noticed this difference:
![unknown](https://user-images.githubusercontent.com/72040129/114808036-7e433400-9d75-11eb-90ce-5e1b75a6c731.png)

**Comment by truong-bui** [comment]
Hi @terishrimp, thank you for reporting bug, I'll investigate this issue.

**Comment by truong-bui** [comment]
@terishrimp, you shouldn't worry about the memory leak in Async Loading Screen. All the pointers in the plugin code are shared pointers, which will be garbage collected in the end anyway. There is no manual memory allocation in the plugin source code, I think it may take an amount of time for GC to collect all the Slate pointers. However, if there is a memory leak in the Slate module or MoviePlayer module, it's out of my ability.

**Comment by terishrimp** [comment]
Hey @truong-bui, fair enough. I have tried allowed the level proceeding the loading screen ample time for GC to see if the memory decreases but it doesn't. Thanks for looking into it! I'll go ahead and do further research myself.
