### ISSUE TITLE
Format Problem on IOS

### ISSUE THREAD

**Issue by Maxmystere** [truong-bui/AsyncLoadingScreen#21]
Images works well on computer but I have a problem when using it on my Ipad where the image will always appear square despite not being square

Original Image : 
![OriginalImage](https://user-images.githubusercontent.com/24446198/116723918-4a584780-a9e0-11eb-92a1-3084610a8d73.jpg)

Mac Example :
<img width="1924" alt="LoadingMacScreenshot" src="https://user-images.githubusercontent.com/24446198/116723937-517f5580-a9e0-11eb-8bcc-ed2109cbc345.png">

IOS Example :
![LoadingIOSScreenshot](https://user-images.githubusercontent.com/24446198/116724063-78d62280-a9e0-11eb-9532-a1cf3c7c99b5.PNG)

Is there any fix possible or did i put wrong parameters ?

**Comment by truong-bui** [comment]
Hi, have you tried to change the Image Stretch option in Background?
![image](https://user-images.githubusercontent.com/1840964/116733664-91612f80-aa16-11eb-9d1b-c5a8a9f98e36.png)

**Comment by Maxmystere** [comment]
I will retry later but since it was working on PC i didn't put too much effort

**Comment by Maxmystere** [comment]
I tested all mode and it seems that some of them are working but the ones I need are sized like the image was square despite it being 2:1

**Comment by truong-bui** [comment]
Try to change the Image Stretch option to Scale To Fill

**Comment by Maxmystere** [comment]
Scale to fill is working but i'd want image to be scaled to Fit (X and Y) which is working perfectly on computer but not on IOS

**Comment by truong-bui** [comment]
> 
> 
> Scale to fill is working but i'd want image to be scaled to Fit (X and Y) which is working perfectly on computer but not on IOS

Then I think you are mostly using the wrong resolution for IOS, Ipad's resolution isn't 16:9, try to use a different image resolution for Ipad instead

**Comment by Maxmystere** [comment]
Image resolution on IOS and Android devices are forced to be power of 2 so to maintain a 16/9ish image I need to have my image 2048/1024
I will investigate on my side

**Comment by Maxmystere** [comment]
So I managed to find the problem for anyone encountering it later
For it to be sized well when in the loading screen you need to set `Compression Settings : UserInterface2D`
