### ISSUE TITLE
Movies don't display outside of editor (4.26)

### ISSUE THREAD

**Issue by professionaljones** [truong-bui/AsyncLoadingScreen#23]
Hi there! I've been having an issue with the plugin recently with packaged builds. Within the editor, both the tips widget and movies play as intended but in packaged builds, only the widget appears. I have recreated my project and used other projects with the same version of the plugin (latest from Marketplace at time of writing) and it is only in this specific project that it does not work. It is seemingly related to the load order of all of the plugins enabled, which is hard to test without breaking the project as a whole. 
![ALS - Movie in Editor](https://user-images.githubusercontent.com/3934211/119039394-3752ea80-b982-11eb-9561-6368c326181d.png)
![ALS - No movie](https://user-images.githubusercontent.com/3934211/119039395-3752ea80-b982-11eb-829b-a203450142a7.png)

**Comment by professionaljones** [comment]
Okay, after doing some more testing, it seems like what is getting in the way is the fact that I was packaging for both Windows and Linux. For the time being it looks like they will have to be separate. Is there any way to overcome this?

**Comment by truong-bui** [comment]
Glad that you have found the problem, I think you should build for only one platform each time.
