### ISSUE TITLE
Complete Loading screen does not hide Loading text and throbber

### ISSUE THREAD

**Issue by helo1313** [truong-bui/AsyncLoadingScreen#29]
Hi, so in my game i want to have a press any key to continue (hide loading screen), so i set this up in Async Loading Screen and every thing is fine with the exception of one, then the loading is complete, the "Press any key" Text shows in the center, but the Loading text and throbber is not hideing at the bottom, and thats very strange. How can i set the loading text hide when the loading complete text shows up ? Is this a bug ? or there is a bool in config that i does not see?
![Bez tytułu](https://user-images.githubusercontent.com/62700189/124902278-12264400-dfe3-11eb-8fd5-6b734e27a219.png)

**Comment by truong-bui** [comment]
Hi, I'll implement it in the next update
