### ISSUE TITLE
Image Sequence Not playing while loading...

### ISSUE THREAD

**Issue by amirslayer** [truong-bui/AsyncLoadingScreen#33]
hey there, I have set an image Sequence based on your Tutorials and it freezes on image index 0 until the game load is completed, then it starts playing!

**Comment by truong-bui** [comment]
Well, it's weird. There are some people got problems with the Image Sequence loading icon but I'm not able to reproduce the issue on my side. I will investigate this, thanks.

**Comment by navdownsmash** [comment]
Hi @amirslayer,
Can you share that project with @truong-bui? My PR may fix this bug in short term.

Regards
Nav

**Comment by truong-bui** [comment]
I'll fix this issue and update to 4.27 in the weekend

**Comment by truong-bui** [comment]
This's fixed in version 1.3.0, please update your plugin, thanks.
