### ISSUE TITLE
FThrobberSettings is undefined at this point, missed include or forward declaration

### ISSUE THREAD

**Issue by norlin** [truong-bui/AsyncLoadingScreen#36]
The subj.

https://github.com/truong-bui/AsyncLoadingScreen/blob/b984d1900aa97c5a60d6411e69412ecda064e296/Source/AsyncLoadingScreen/Public/SLoadingWidget.h#L27

**Comment by truong-bui** [comment]
Thanks for the report, @norlin. Fixed!
