### ISSUE TITLE
AnimatingImageSequence is not called immediately when StartupLoadingScreen is running.

### ISSUE THREAD

**Issue by HongJooSung** [truong-bui/AsyncLoadingScreen#37]
![image](https://user-images.githubusercontent.com/42930611/133403046-4e188d02-64d4-4892-a59d-ba1173fb4375.png)

**There is a problem that ImageSequence does not work because this part cannot be called immediately. Any solution? The settings are identical to yours.**

**Comment by truong-bui** [comment]
Hi @HongJooSung, this issue is fixed in the new version 1.3.0, please update your plugin.

**Comment by HongJooSung** [comment]
@truong-bui It's completely resolved. thank you!
