### ISSUE TITLE
Loading screen doesn't work in multiplayer game

### ISSUE THREAD

**Issue by Natyen189** [truong-bui/AsyncLoadingScreen#4]
- The plugin works great so far but now if i use the command ```"ServerTravel"``` instead of ```"Open"``` the loading doesnt show up anymore. I need to use ```"ServerTravel"``` cause im want to do a seamless travel in multiplayer game :( So how can i fix this issue?

Thanks!

**Comment by truong-bui** [comment]
> 
> 
>     * The plugin works great so far but now if i use the command `"ServerTravel"` instead of `"Open"` the loading doesnt show up anymore. I need to use `"ServerTravel"` cause im want to do a seamless travel in multiplayer game :( So how can i fix this issue?
> 
> 
> Thanks!

Unfortunately, the plugin only works with "hard" level loading like **Open Level** command which is everything in the old level will be destroyed completely before loading a new level. **ServerTravel**, however, is not a 'hard' level loading command

**Comment by Natyen189** [comment]
Oh i see, thanks for the info 👍
