### ISSUE TITLE
How To convert project to C++

### ISSUE THREAD

**Issue by Thailoz** [truong-bui/AsyncLoadingScreen#40]
Hi by convert the project to C++ from BP are you revering to Nativizing under the package options in project settings?

**Comment by truong-bui** [comment]
Just add any c++ class but you don't need to convert the project to c++ to use plugins anymore. Just download and install the pre-built version on Marketplace via Epic Games Launcher.

**Comment by Thailoz** [comment]
Oh so just to clarify i can just package the game and it should work No C++ class needed

**Comment by truong-bui** [comment]
Yeah

**Comment by Thailoz** [comment]
Thankyou for the prompt replies
