### ISSUE TITLE
None Use GetMoviePlayer Version

### ISSUE THREAD

**Issue by laycnc** [truong-bui/AsyncLoadingScreen#41]
Currently, AsyncLoadingScreen is supported only for "OpenLevel".
My game is huge, so I use async streams instead of "OpenLevel" to load levels, cutscenes, etc.

https://docs.unrealengine.com/4.27/ja/ProgrammingAndScripting/Slate/InGameUI/

There is a way to add a Slate to the GameViewport directly instead of using GetMoviePlayer.
Can you provide an API that uses GameViewport?

**Comment by truong-bui** [comment]
If you're using load stream level I suggest just using UMG for your loading screen, don't use Slate.

**Comment by laycnc** [comment]
Thank you for your answer.
I will close the issue.
