### ISSUE TITLE
Hello! I am using an asynchronous loading screen. thank you! But I have one problem.

### ISSUE THREAD

**Issue by HongJooSung** [truong-bui/AsyncLoadingScreen#42]
![image](https://user-images.githubusercontent.com/42930611/141966030-21f0a450-bb02-4aec-9d3d-6ade3e9ba6a4.png)

GetMoviePlayer()->IsLoadingFinished()  It does not return true even though the map has finished loading. Do you know the cause?

What I want is for that function to be called and the loading screen to end.

**Comment by ip01119** [comment]
> ![image](https://user-images.githubusercontent.com/42930611/141966030-21f0a450-bb02-4aec-9d3d-6ade3e9ba6a4.png)
> 
> GetMoviePlayer()->IsLoadingFinished() It does not return true even though the map has finished loading.  Do you know the cause?
> 
> What I want is for that function to be called and the loading screen to end.
