### ISSUE TITLE
Custom Function call when Loading Screen is about to end?

### ISSUE THREAD

**Issue by CanisHelix** [truong-bui/AsyncLoadingScreen#49]
I'd like to call a function in my GameMode right before the loading/transition widget's unload. Is this possible?

I couldn't find in the source code where you unload the widgets when the new map is ready.

**Comment by truong-bui** [comment]
I don't think it's possible to access any game-play logic during the loading screen. I don't unload the widget, it's removed by the engine when the PostLoadMapWithWorld delegate triggers. You can check the MoviePlayer plugin's source code.

**Comment by CanisHelix** [comment]
Thanks, I'll look into PostLoadMapWithWorld in the engine
