### ISSUE TITLE
Compatibilities with Bink Media

### ISSUE THREAD

**Issue by rhesa-beg** [truong-bui/AsyncLoadingScreen#52]
Hello Mr. Truong Bui,
I found out that if I enable Electra Player, the plugin stops working. Is there a workaround because my projects currently rely on both.
Thank you.

**Comment by truong-bui** [comment]
Unfortunately, I'm not familiar with the Electra Player plugin, so I couldn't help with this issue. But when there are conflicts between plugins, you may have to choose to use only one of those.

**Comment by rhesa-beg** [comment]
I am sorry. After further testing, the one that cause the player to not work is Bink Media. Sorry for the misleading question, but do you have a solution in mind regarding Bink Media?

**Comment by rhesa-beg** [comment]
Just bink the video you use for the loading screen. It solves the problem.
