### ISSUE TITLE
Unreal 5.3 loading screen just doesn't work

### ISSUE THREAD

**Issue by rever96** [truong-bui/AsyncLoadingScreen#80]
![image](https://github.com/truong-bui/AsyncLoadingScreen/assets/19595534/ad6c0905-6ea2-44b2-9e72-425e463be3de)
![image](https://github.com/truong-bui/AsyncLoadingScreen/assets/19595534/71d71e06-91db-4df6-a66f-21830012b855)

I have blueprint that call OpenLevel by Name Node. new level loaded correctly but no loading screen appeared

**Comment by chaselavancher** [comment]
I am also having the same issue, I went back over the tutorial where he sets the backgrounds to any level and realized I did not have the set background manually checked, I'm going to test this out in the morning. I'll let you know if this fixed that. Did you by chance try checking that box and then in your widget, also making sure that you call the "Set background index"? In this case it also looks like you just have 1 background for your level, make sure that the index number is set to 0.

**Comment by truong-bui** [comment]
> I have blueprint that call OpenLevel by Name Node. new level loaded correctly but no loading screen appeared

> I am also having the same issue...

Can you please provide the project link, if possible? I will take a look at it. Note that you need to play a Standalone Game or use Quick Launch for the MoviePlayer module to launch. **Play In Editor (PIE) won't work**!

![image](https://github.com/truong-bui/AsyncLoadingScreen/assets/1840964/ab1f4cd1-a1f5-4476-8a29-0a30da32943e)

Also, check if the plugin conflicts with other plugins. For example: "Pre-Load Screen Movie Player." Please make sure that you don't have unused plugins enabled.

**Comment by chaselavancher** [comment]
I can verify that this is indeed not working @truong-bui
