### ISSUE TITLE
Loader not showing on Linux/Steamdeck

### ISSUE THREAD

**Issue by TadDancer** [truong-bui/AsyncLoadingScreen#83]
Hey there, is it possible that there's an issue running this plugin on Linux/Steamdeck (Tried both, Ubuntu and SteamOS)
I'm using mp4 Videos in a very basic setting, so no widgets or anything. On windows it works flawlessly (thanks by the way, it's very helpful!)

Any insights there?

**Comment by truong-bui** [comment]
Hi, I have not had Linux or Steamdeck to test the plugin. But it seems like it's an issue with MoviePlayer on Linux. There may be someone familiar with Linux, and Steamdeck can help you.

**Comment by TadDancer** [comment]
Hey, thanks for the reply, that was already helpful.
I switched the video format to Bink and enabled the Bink Media Player in my project, now it works (In case someone stumbles over this, that's a way to go)
