### ISSUE TITLE
How to remove a whiter Bar in bottom?

### ISSUE THREAD

**Issue by aadeshrao123** [truong-bui/AsyncLoadingScreen#90]
![image](https://github.com/truong-bui/AsyncLoadingScreen/assets/55663044/502c2c83-ef44-46e1-9940-e83123983211)

**Comment by aadeshrao123** [comment]
I am getting a white bar at the bottom of my loading screen. Can please anyone help me how to remove it?

**Comment by truong-bui** [comment]
Hi, you change it in the Layout section, set Alpha to 0 if you want to hide the background.

![image](https://github.com/truong-bui/AsyncLoadingScreen/assets/1840964/c2187d29-38a4-4650-b34c-526cd082bcd0)

**Comment by aadeshrao123** [comment]
Thank you for the help
