### ISSUE TITLE
error when packaged

### ISSUE THREAD

**Issue by Be1ow** [truong-bui/AsyncLoadingScreen#98]
I added a menu and a world to walk in to test the plugin, when I packaged the game and ran the exe file this error popped up "Plugin 'AsyncLoadingScreen' failed to load because module 'AsyncLoadingScreen' could not be found.  Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project." and wont let me start

**Comment by truong-bui** [comment]
It seems like your project is blueprint-based. You are trying to use the plugin when you haven't installed it properly. You can download the plugin on GitHub, add it to your Plugins folder, and compile it again.

**Comment by Be1ow** [comment]
I found out that is was a packaging error, I fixed it
