### ISSUE TITLE
Show a black screen after loading scene disappear. Have to click to show the loaded level scene.

### ISSUE THREAD

**Issue by tiantian20007** [truong-bui/AsyncLoadingScreen#99]
After connected to a DS server, the loading scene show up. Afte loading scene disappear, a black screen show up, have to click mouse to make the black screen gone, and the real scene showed.
I called StopLoadingScene in the player pawn's Beginplay.
What I want is the real scene show up automatically when the loading scene disappear after player pawn is ready, without the black screen.
Engine version is 5.3.2. And the level is using world partition.
My setting is in the attackment image.
![捕获](https://github.com/truong-bui/AsyncLoadingScreen/assets/406098/ccd95e8f-300f-4a84-8fa1-a3d88e5cbd53)

**Comment by truong-bui** [comment]
Hi, just disable the **Wait for Manual Stop** setting

**Comment by tiantian20007** [comment]
After I disable WaitforManualStop, the loading screen will disappear automatically without waiting for my StopLoadingScene in PlayerPawn.
